const sentences = [
        "Greetings, Ms Erin", 
        "Sometimes I sit and wonder...", 
        "what path my life would've taken had I not met you.",
        "Well it would be exactly the same except...",
        "I would have one less stupid, embarrassing friend",
        "(Oh the bliss!)",
        "However, since today's your special day...",
        "I'll say only nice things about you today.",
        "You are composed",
        "(giggles like a maniac in serious situations)",
        "You are hilarious",
        "(makes the unfunniest dad jokes)",
        "You are self-aware",
        "(stares at people like a creep)",
        "You are fearless",
        "(this might actually be true)",
        "And over the past few months...",
        "It's been incredibly fun with you",
        "And I got to discover the most wonderful thing on planet earth",
        "It starts with an 'E' and ends with an 'N'",
        "...",
        "EVASION (Tax)",
        "Hehehe",
        "Most friendships have an expiry date.",
        "However...",
        "You are a ray of sunshine...",
        "and I'm glad we met",
];

export default sentences;
